apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  DATABASE_HOST: "{{ .Values.configmap.database.host }}"
  DATABASE_PORT: "{{ .Values.configmap.database.port }}"
  DATABASE_NAME: "{{ .Values.configmap.database.name }}"
  PHX_HOST: "https://{{ index .Values.ingress.hosts 0 }}"
