apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  AUTH_USERNAME: "{{ .Values.secret.basicAuth.username }}"
  AUTH_PASSWORD: "{{ .Values.secret.basicAuth.password }}"
  API_TOKEN: "{{ .Values.secret.apiToken }}"
  SECRET_KEY_BASE: "{{ .Values.secret.secretKeyBase }}"
